# Generated by Django 5.1.1 on 2024-10-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantuty',
            field=models.IntegerField(default=0),
        ),
    ]
