# Generated by Django 5.1.1 on 2024-10-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='validate_product',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
