# Generated by Django 5.1.1 on 2024-10-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_quantuty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantuty',
            new_name='quantity',
        ),
    ]
