# Generated by Django 5.1.1 on 2024-10-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='validate_product',
        ),
    ]
