# Generated by Django 5.1.1 on 2024-11-08 09:45

import django.db.models.deletion
import mptt.fields
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_category_level_alter_category_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='აღწერა'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ka',
            field=models.TextField(null=True, verbose_name='აღწერა'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='სახელი'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ka',
            field=models.CharField(max_length=100, null=True, verbose_name='სახელი'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='სახელი'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category', verbose_name='მშობელი'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='სლაგი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='store.category', verbose_name='კატეგორია'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=models.TextField(null=True, verbose_name='ქვეყნის დასახელება'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='აღწერა'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='products/', verbose_name='სურათი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_weight',
            field=models.FloatField(null=True, verbose_name='მინიმალური წონა'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='სახელი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='ფასი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(max_length=50, null=True, verbose_name='ხარისხი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='რაოდენობა'),
        ),
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.IntegerField(default=0, verbose_name='ვარსკვლავი'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='product_tags', to='store.producttags', verbose_name='ტეგები'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(null=True, verbose_name='წონა'),
        ),
        migrations.AlterField(
            model_name='producttags',
            name='name',
            field=models.CharField(max_length=100, verbose_name='სახელი'),
        ),
    ]
